spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://172.28.7.32:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/itoken-enda-lin/itoken-config-file
          force-pull: true
          search-paths: repo
          username: account
          password: password
  zipkin:
    base-url: http://172.28.7.32:9411

server:
  port: 8888

eureka:
  client:
    server-url:
      defaultZone: http://172.28.7.36:8761/eureka/